### ISSUE TITLE
Energy crystal item module type

### ISSUE THREAD

**Issue by DrizztDoUrden** [DrizztDoUrden/UHHD#5]
#### Blue
+100% capacity
+100% fountain replenishment speed
#### Black
-40% fountain replenishment speed
Every creep death in range of 500 provides 1 charge, 15 for boss.
#### Red
-50% fountain replenishment speed
Item gets 1 charge for each (20% of your max HP) damage you deal

### Tasks
- [ ] Items.EnergyCrystal class
- [x] Design crystals
- [ ] Items.BasicEnergyCrystal class - configurable default crystal of item with slot
- [ ] Items.EnchancedEnergyCrystal class - crystal enchancing properties of basic crystal of item
- [ ] Blue crystal
- [ ] Red crystal
- [ ] Black crystal
- [ ] Item to test crystals with
- [ ] Crystals shop
